---
- name: Deploy Grafana in Container
  hosts: my_servers
  vars:
    grafana_image: "docker.io/grafana/grafana"
    grafana_container_name: "grafana"
    grafana_data: "/var/lib/grafana"
    grafana_base: "/tmp/grafana"
    grafana_ports: "3004:3000"
    grafana_env:
      GF_SECURITY_ADMIN_USER: "redhat"
      GF_SECURITY_ADMIN_PASSWORD: "redhat"

  tasks:
    - name: Create the directory /tmp/grafana
      file:
        path: /tmp/grafana
        state: directory
        mode: '0777'
      tags:
        - create_directory

    - name: Pull Grafana image
      containers.podman.podman_image:
        name: "{{ grafana_image }}"
        tag: "latest"
      tags:
        - pull_image

    - name: Run Grafana container
      containers.podman.podman_container:
        name: "{{ grafana_container_name }}"
        image: "{{ grafana_image }}"
        state: started
        ports:
          - "{{ grafana_ports }}"
        env:
          "{{ grafana_env | to_json }}"  # Convert dictionary to JSON format
        volumes:
          - "{{ grafana_base }}:{{ grafana_data }}"
      tags:
        - run_container

    - name: Verify Grafana container is running
      command: podman ps --filter "name={{ grafana_container_name }}" --format "{{'{{.Status}}'}}"
      register: container_status
      tags:
        - verify_container

    - name: Verify Grafana availability with curl
      command: curl http://localhost:3004/login
      register: grafana_response
      ignore_errors: yes
      tags:
        - verify_grafana
