---
- name: Ensure Tomcat container is installed and running
  hosts: my_servers
  vars:
    tomcat_image: "docker.io/library/tomcat:latest"
    jmx_agent_url: "https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/0.16.1/jmx_prometheus_javaagent-0.16.1.jar"
    jmx_agent_dest: "/tmp/tomcat/jmx_prometheus_javaagent-0.16.1.jar"
    webapps_dir: "/tmp/tomcat/webapps"
    logs_dir: "/tmp/tomcat/logs"
    war_source_path: "/home/madhur/SampleWebApp.war"  # Path on the Ansible controller
    war_dest_path: "/tmp/tomcat/SampleWebApp.war"  # Path on the target server
    container_name: "tomcat"  # Name of the container
    container_webapps_path: "/usr/local/tomcat/webapps/"  # Path inside the container
    setenv_content: |
      JAVA_OPTS="$JAVA_OPTS -javaagent:/usr/local/tomcat/bin/jmx_prometheus_javaagent-0.16.1.jar=9999:/usr/local/tomcat/bin/tomcat.yml"
      export JAVA_OPTS
    setenv_dest: "/tmp/tomcat/setenv.sh"
    tomcat_yml_content: |
      lowercaseOutputLabelNames: true
      lowercaseOutputName: true
      whitelistObjectNames: ["java.lang:type=OperatingSystem"]
      blacklistObjectNames: []
      rules:
        - pattern: 'java.lang<type=OperatingSystem><>(committed_virtual_memory|free_physical_memory|free_swap_space|total_physical_memory|total_swap_space)_size:'
          name: os_$1_bytes
          type: GAUGE
          attrNameSnakeCase: true
        - pattern: 'java.lang<type=OperatingSystem><>((?!process_cpu_time)\w+):'
          name: os_$1
          type: GAUGE
          attrNameSnakeCase: true
    tomcat_yml_dest: "/tmp/tomcat/tomcat.yml"
    tomcat_container_name: "tomcat"
    tomcat_ports:
      - "8075:8080"
      - "9999:9999"
    container_volumes:
      - "{{ jmx_agent_dest }}:/usr/local/tomcat/bin/jmx_prometheus_javaagent-0.16.1.jar"
      - "{{ setenv_dest }}:/usr/local/tomcat/bin/setenv.sh"
      - "{{ tomcat_yml_dest }}:/usr/local/tomcat/bin/tomcat.yml"
      - "{{ logs_dir }}:/usr/local/tomcat/logs"
      - "{{ webapps_dir }}:/usr/local/tomcat/webapps"
      - "{{ war_dest_path }}:/usr/local/tomcat/webapps/ROOT.war"
    tomcat_url: "http://localhost:8075/"
    tomcat_status_filter: "name=tomcat"

  tasks:
    - name: Check if Tomcat container exists
      command: podman ps -a --filter "name={{ tomcat_container_name }}" --format "{{'{{.Status}}'}}"
      register: container_status
      ignore_errors: yes
      failed_when: false
      tags: verify_container

    - name: Set fact if Tomcat container is not running or exists but stopped
      set_fact:
        tomcat_not_running: "{{ container_status.stdout is defined and container_status.stdout == '' }}"
        tomcat_exists_stopped: "{{ container_status.stdout is defined and 'exited' in container_status.stdout | lower }}"
      tags: verify_container

    - name: Start Tomcat container if it exists but is stopped
      command: podman start {{ tomcat_container_name }}
      when: tomcat_exists_stopped
      tags: start_container

    - name: Deploy Tomcat if not running or not exists
      block:
        - name: Pull the Tomcat container image
          containers.podman.podman_image:
            name: "{{ tomcat_image }}"
            tag: latest
          tags: pull_image

        - name: Create necessary directories if not exist
          file:
            path: "{{ item }}"
            state: directory
          with_items:
            - /tmp/tomcat
            - /tmp/tomcat/logs
            - /tmp/tomcat/webapps
          tags: create_directories
          
        - name: Ensure SampleWebApp.war file exists on the controller
          stat:
            path: "{{ war_source_path }}"
          register: war_file
          tags: check_war
           
        - name: Copy SampleWebApp.war to /tmp directory on target server
          copy:
             src: "{{ war_source_path }}"
             dest: "{{ war_dest_path }}"
          tags: copy_war
             
        - name: Download JMX Prometheus Java agent JAR
          get_url:
            url: "{{ jmx_agent_url }}"
            dest: "{{ jmx_agent_dest }}"
          tags: download_jmx

        - name: Create setenv.sh for Tomcat
          copy:
            content: "{{ setenv_content }}"
            dest: "{{ setenv_dest }}"
            mode: '0755'
          tags: configure_tomcat

        - name: Create tomcat.yml for JMX exporter
          copy:
            content: "{{ tomcat_yml_content }}"
            dest: "{{ tomcat_yml_dest }}"
          tags: configure_tomcat

        - name: Run Tomcat container with JMX exporter
          containers.podman.podman_container:
            name: "{{ tomcat_container_name }}"
            image: "{{ tomcat_image }}"
            state: started
            ports: "{{ tomcat_ports }}"
            volumes: "{{ container_volumes }}"
          tags: run_container

        - name: Check if Tomcat container is running
          command: podman ps -q --filter "name={{ tomcat_container_name }}"
          register: running_container_id
          failed_when: false
          tags: verify_container

        - name: Verify sample application is accessible
          command: curl http://localhost:8075
          ignore_errors: yes
          tags: verify_application
      when: tomcat_not_running

    - name: Check if Tomcat container is running
      command: podman ps -q --filter "name={{ tomcat_container_name }}"
      register: running_container_id
      failed_when: false
      tags: deploy_war

    - name: Copy WAR file to container
      command: podman cp "{{ war_dest_path }}" {{ container_name }}:"{{ container_webapps_path }}"
      when: running_container_id is defined and running_container_id.stdout != ''
      tags: deploy_war
